project_id = "rolitmcxydholgsxpvwa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
api_url = "http://127.0.0.1:54321"
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = {"enabled": true}

[auth]
enabled = true
site_url = "https://chequealo.ar"
additional_redirect_urls = ["https://chequealo.ar", "https://chequealo.ar/auth", "https://www.chequealo.ar", "https://www.chequealo.ar/auth", "http://127.0.0.1:3000", "http://127.0.0.1:8080/auth"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54328
inspector_port = 54329

[functions.create-payment-preference]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = false

[functions.send-review-reminders]
verify_jwt = false

[functions.send-custom-auth-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.billing-get-plans]
verify_jwt = false

[functions.billing-get-subscription]
verify_jwt = true

[functions.billing-subscribe]
verify_jwt = true

[functions.billing-portal]
verify_jwt = true

[functions.billing-cancel]
verify_jwt = true

[functions.send-completion-confirmations]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false