// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rolitmcxydholgsxpvwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbGl0bWN4eWRob2xnc3hwdndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDk0MzIsImV4cCI6MjA3MzIyNTQzMn0.A8lUa6pBn1aW_b9n_9BXFmH19fiKcQioG1bfzObZWsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});